apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-3tsa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yzxd-tenant/nodejs-users/simple-nodejs-app-3tsa@sha256:b4f87267dff3bb4571724d72c8947d8daf77711b11dd031e71dc988d01cad177
        name: my-nodejs
        resources: {}
status: {}
